### PR TITLE
Created a beginner level

### PR DESCRIPTION
**Pull request by H1manshu21**
Added 6 horizontal grids and 4 vertical grids

### CODE REVIEW

**Comment by walterbender** [comment]
A few issues:

It seems that you changed the game to always be beginner level instead of starting beginner and ending up normal play.

There are too many mines (cookies) in beginner mode.

The dot size needs to change when in beginner mode.

Lots of unrelated changes to the code.

**Comment by walterbender** [comment]
Also, there is an error: game instance has no attribute _game_time_seconds on Line 139

**Comment by walterbender** [comment]
I was thinking -- maybe a better approach would be to keep the grid size the same but simply start with fewer mines. Maybe start with just one mine and each time you win, the number of mines increases by 1.

Should be easier to implement and would be just as effective as introducing the game to beginners.

**Comment by quozl** [comment]
Tested bca1c91.

Also saw a "Keep Error" probably related to `_game_time_seconds`, and warnings on line 294 trying to remove source of `self._timeout_id`.

**Pull request closed without merging**
