### PR TITLE
Port Telepathy static binding to TelepathyGLib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
On sharing the activity, this error occurs;

```
Traceback (most recent call last):
  File "/usr/share/sugar/activities/CookieSearch.activity/SearchActivity.py", line 202, in _shared_cb
    self._new_tube_common(True)
  File "/usr/share/sugar/activities/CookieSearch.activity/SearchActivity.py", line 210, in _new_tube_common
    if self._shared_activity is None:
AttributeError: 'SearchActivity' object has no attribute '_shared_activity'
```

**Comment by rhl-bthr** [comment]
@chimosky any updates on this ?

**Comment by chimosky** [comment]
@quozl @pro-panda changes made kindly review.

**Comment by quozl** [comment]
Tested collaboration and it doesn't work; the same game state is not shown on both laptops I tested with.  There are no relevant tracebacks or errors in logs.  It needs more detailed debugging time than I can spend right now.  Same thing happens on my _master_ branch which I've pushed and opened as a pull request https://github.com/sugarlabs/cookie-search-activity/pull/15.  Collaboration has to work before porting to TelepathyGLib, otherwise we can't tell if porting is successful.

By the way, there's a message to be changed too;

```diff
diff --git a/SearchActivity.py b/SearchActivity.py
index c7075a3..37bf574 100644
--- a/SearchActivity.py
+++ b/SearchActivity.py
@@ -209,7 +209,7 @@ class SearchActivity(activity.Activity):
         """ Joining and sharing are mostly the same... """
         if self.shared_activity is None:
             _logger.debug("Error: Failed to share or join activity ... \
-                _shared_activity is null in _shared_cb()")
+                shared_activity is null in _shared_cb()")
             return
 
         self.initiating = sharer
```

**Comment by rhl-bthr** [comment]
Stale

**Pull request closed without merging**
