### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by quozl**
Best effort update from translate.sugarlabs.org, and updated POT file.

@leonardcj, there are [completed translations](https://translate.sugarlabs.org/projects/CookieSearch/) that I don't know how to get a copy of quickly; how is it done?  e.g. Albanian, `sq`, by @ujdhesa.

### CODE REVIEW

**Comment by quozl** [comment]
@leonardcj, never mind, got them all, using `wget` and a bit of scripting.

**Comment by leonardcj** [comment]
Sorry for the late reply Quozl.  I'm guessing you figured out that given
the regular URL format of Pootle links, it should be easy to autogenerate
download links given a list of language codes to be pulled.

**Comment by quozl** [comment]
Yes, thanks.

I was just wishing for something better.  :grin:

What I have so far works, but does pull empty languages, so I'll look
for a way to avoid that.  Python, import requests, HTML parsing,
probably.

**Comment by leonardcj** [comment]
The ultimate solution is a step to the soon-expected version of Pootle.  It
restores a CVS interface that we had previously covered with Sayamindu's
scripts.  The new pootle-fs filesystem is the path back to a level of repo
integration that we used to enjoy.

**Pull request merged**
